# For more information: https://laravel.com/docs/sail
version: '3'
services:
    http:
        build:
            context: ./
            dockerfile: Dockerfile
        image: http
        ports:
            - '80:80'
            - '81:81'
            - '443:443'
        environment:
            TZ: 'Atlantic/Canary'
        volumes:
            - './www:/var/www/'
            - './apache2:/etc/apache2'
            - './extraFiles:/extraFiles'
#        depends_on:
#            - mysql
#    mysql:
#        image: 'mysql:latest'
#        ports:
#            - '3306:3306'
#        environment:
#            MYSQL_ROOT_PASSWORD: '1234'
#            MYSQL_DATABASE: 'http'
#            MYSQL_USER: 'yeray'
#            MYSQL_PASSWORD: '1234'
#            MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
#            TZ: 'Atlantic/Canary'